import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import { Header } from "@/src/component/header";
import { cookies } from "next/headers";
import { TOKEN_KEY } from "@/src/app/constant/common";
import { getMe, getProfileImage } from "@/src/fetcher/profile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hasToken = !!cookies().get(TOKEN_KEY);
  let profileImage = "";
  try {
    if (hasToken) {
      const me = await getMe();
      profileImage = await getProfileImage(me.id);
    }
  } catch (e) {
    console.error(e);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100vh] min-w-[100vw] w-[100vw] bg-sky-200 bg-gradient-to-b from-gray-50 flex flex-col`}
      >
        <Header hasToken={hasToken} profileImage={profileImage} />
        <main className="grow flex flex-col">{children}</main>
      </body>
    </html>
  );
}
